spring:
  application:
    name: ureca_miniproject2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ureca_miniproject2
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.springframework.security: debug

server:
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

